/*
###############################################################
#  Generated by:      Cadence Innovus 18.16-s077_1
#  OS:                Linux x86_64(Host ID s2424)
#  Generated on:      Fri Jan  8 00:43:31 2021
#  Design:            counter
#  Command:           saveNetlist output/counter_pnr.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 18.15-s055_1
// Generated on: Jan  7 2021 23:46:05 CET (Jan  7 2021 22:46:05 UTC)
// Verification Directory fv/counter 
module counter (
	out, 
	enable, 
	clk, 
	reset);
   output [7:0] out;
   input enable;
   input clk;
   input reset;

   // Internal wires
   wire FE_PHN204_FE_OFN171_reset;
   wire FE_PDN203_n_62;
   wire FE_PDN202_FE_OFN166_out_7__65;
   wire FE_PDN201_n_62;
   wire FE_PDN200_FE_OFN28_out_3;
   wire FE_PHN199_FE_OFN171_reset;
   wire FE_PHN198_FE_OFN171_reset;
   wire FE_PHN197_FE_OFN171_reset;
   wire FE_PHN196_FE_OFN171_reset;
   wire FE_PHN195_FE_OFN171_reset;
   wire FE_PHN194_FE_OFN171_reset;
   wire FE_PHN193_FE_OFN171_reset;
   wire FE_PHN192_FE_OFN171_reset;
   wire FE_PHN191_FE_OFN171_reset;
   wire FE_PDN190_FE_OFN165_enable;
   wire FE_PDN189_FE_OFN205_n;
   wire FE_PDN188_FE_OFN165_enable;
   wire FE_PDN187_n_62;
   wire FE_PDN186_FE_OFN17_reset;
   wire FE_PDN185_FE_OFN168_n;
   wire FE_PDN184_FE_OFN28_out_3;
   wire FE_PDN183_n_85;
   wire FE_PDN182_n_46;
   wire FE_PDN181_n_92;
   wire FE_PDN180_FE_OFN32_out_1;
   wire FE_PDN179_n_69;
   wire FE_PDN178_n_0;
   wire FE_PDN177_FE_OFN205_n;
   wire FE_PDN176_FE_OFN204_n;
   wire FE_PDN175_FE_OFN12_reset;
   wire FE_PDN174_FE_OFN165_enable;
   wire CTS_10;
   wire CTS_9;
   wire CTS_8;
   wire CTS_6;
   wire CTS_7;
   wire CTS_5;
   wire CTS_4;
   wire CTS_3;
   wire CTS_1;
   wire CTS_2;
   wire FE_OFN173_enable;
   wire FE_OFN172_FE_OFN27_out_4;
   wire FE_OFN171_reset;
   wire FE_OFN169_n;
   wire FE_OFN168_n;
   wire FE_OFN218_n_71;
   wire FE_OFN214_n_72;
   wire FE_OFN213_n_90;
   wire FE_OFN210_n_42;
   wire FE_OFN209_n_35;
   wire FE_OFN207_n_62;
   wire FE_OFN206_n_83;
   wire FE_OFN205_n;
   wire FE_OFN204_n;
   wire FE_OFN203_n_56;
   wire FE_OFN201_n_48;
   wire FE_OFN200_FE_OFN45_n_3;
   wire FE_OFN198_FE_OFN8_enable;
   wire FE_OFN196_n_0;
   wire FE_OFN195_FE_OFN28_out_3;
   wire FE_OFN193_out_3;
   wire FE_OFN192_n_77;
   wire FE_OFN190_n_53;
   wire FE_OFN188_FE_OFN27_out_4;
   wire FE_OFN185_n_58;
   wire FE_OFN184_n_10;
   wire FE_OFN183_FE_OFN23_out_5;
   wire FE_OFN182_n_2;
   wire FE_OFN180_n_95;
   wire FE_OFN179_n_47;
   wire FE_OFN178_n_55;
   wire FE_OFN177_FE_OFN17_reset;
   wire FE_OFN175_n_41;
   wire FE_OFN174_out_0__58;
   wire FE_OFN172_FE_OFN30_out_2;
   wire FE_OFN171_n_51;
   wire FE_OFN168_n_65;
   wire FE_OFN167_out_7__65;
   wire FE_OFN166_out_7__65;
   wire FE_OFN165_enable;
   wire FE_OFN162_out_2;
   wire FE_OFN155_n;
   wire FE_OFN151_n;
   wire FE_OFN149_n;
   wire FE_OFN148_n;
   wire FE_OFN145_n;
   wire FE_OFN144_n_96;
   wire FE_OFN142_n_94;
   wire FE_OFN138_n_88;
   wire FE_OFN136_n_85;
   wire FE_OFN135_n_84;
   wire FE_OFN133_n_82;
   wire FE_OFN132_n_80;
   wire FE_OFN129_n_76;
   wire FE_OFN124_n_75;
   wire FE_OFN123_n_74;
   wire FE_OFN119_n_70;
   wire FE_OFN117_n_68;
   wire FE_OFN116_n_67;
   wire FE_OFN113_n_149;
   wire FE_OFN112_n_66;
   wire FE_OFN111_n_63;
   wire FE_OFN110_n_60;
   wire FE_OFN109_n_148;
   wire FE_OFN108_n_61;
   wire FE_OFN107_n_59;
   wire FE_OFN106_n_57;
   wire FE_OFN103_n_58;
   wire FE_OFN97_n_52;
   wire FE_OFN94_n_51;
   wire FE_OFN90_n_47;
   wire FE_OFN88_n_46;
   wire FE_OFN86_n_87;
   wire FE_OFN81_n_87;
   wire FE_OFN78_n_87;
   wire FE_OFN76_n_87;
   wire FE_OFN75_n_49;
   wire FE_OFN71_n_37;
   wire FE_OFN69_n_33;
   wire FE_OFN68_n_24;
   wire FE_OFN66_out_0;
   wire FE_OFN64_out_7;
   wire FE_OFN61_out_0__58;
   wire FE_OFN58_n_11;
   wire FE_OFN57_n_11;
   wire FE_OFN56_n_10;
   wire FE_OFN55_n_10;
   wire FE_OFN51_n_8;
   wire FE_OFN47_n_6;
   wire FE_OFN45_n_3;
   wire FE_OFN42_n_2;
   wire FE_OFN38_n_1;
   wire FE_OFN37_n_0;
   wire FE_OFN32_out_1;
   wire FE_OFN30_out_2;
   wire FE_OFN28_out_3;
   wire FE_OFN25_out_4;
   wire FE_OFN23_out_5;
   wire FE_OFN22_out_6;
   wire FE_OFN21_out_6;
   wire FE_OFN19_reset;
   wire FE_OFN17_reset;
   wire FE_OFN14_reset;
   wire FE_OFN12_reset;
   wire FE_OFN8_enable;
   wire FE_OFN7_enable;
   wire FE_OFN5_enable;
   wire FE_OFN4_enable;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_6;
   wire n_8;
   wire n_10;
   wire n_11;
   wire n_19;
   wire n_22;
   wire n_24;
   wire n_33;
   wire n_35;
   wire n_37;
   wire n_39;
   wire n_41;
   wire n_42;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_148;
   wire n_149;
   wire \out[0]_58 ;
   wire \out[7]_65 ;

   BUFX2 FE_PHC204_FE_OFN171_reset (.Y(FE_PHN204_FE_OFN171_reset),
	.A(FE_PHN194_FE_OFN171_reset));
   BUFX2 FE_PDC203_n_62 (.Y(FE_PDN203_n_62),
	.A(n_62));
   BUFX2 FE_PDC202_FE_OFN166_out_7__65 (.Y(FE_PDN202_FE_OFN166_out_7__65),
	.A(FE_OFN166_out_7__65));
   BUFX2 FE_PDC201_n_62 (.Y(FE_PDN201_n_62),
	.A(FE_PDN203_n_62));
   BUFX2 FE_PDC200_FE_OFN28_out_3 (.Y(FE_PDN200_FE_OFN28_out_3),
	.A(FE_OFN28_out_3));
   BUFX2 FE_PHC199_FE_OFN171_reset (.Y(FE_PHN199_FE_OFN171_reset),
	.A(FE_PHN198_FE_OFN171_reset));
   BUFX2 FE_PHC198_FE_OFN171_reset (.Y(FE_PHN198_FE_OFN171_reset),
	.A(FE_PHN197_FE_OFN171_reset));
   BUFX2 FE_PHC197_FE_OFN171_reset (.Y(FE_PHN197_FE_OFN171_reset),
	.A(FE_PHN191_FE_OFN171_reset));
   BUFX2 FE_PHC196_FE_OFN171_reset (.Y(FE_PHN196_FE_OFN171_reset),
	.A(FE_PHN193_FE_OFN171_reset));
   BUFX2 FE_PHC195_FE_OFN171_reset (.Y(FE_PHN194_FE_OFN171_reset),
	.A(FE_PHN195_FE_OFN171_reset));
   BUFX2 FE_PHC194_FE_OFN171_reset (.Y(FE_OFN171_reset),
	.A(FE_PHN204_FE_OFN171_reset));
   BUFX2 FE_PHC193_FE_OFN171_reset (.Y(FE_PHN193_FE_OFN171_reset),
	.A(FE_OFN171_reset));
   BUFX2 FE_PHC192_FE_OFN171_reset (.Y(FE_PHN192_FE_OFN171_reset),
	.A(FE_PHN196_FE_OFN171_reset));
   BUFX2 FE_PHC191_FE_OFN171_reset (.Y(FE_PHN191_FE_OFN171_reset),
	.A(FE_PHN192_FE_OFN171_reset));
   BUFX2 FE_PDC190_FE_OFN165_enable (.Y(FE_PDN190_FE_OFN165_enable),
	.A(FE_PDN174_FE_OFN165_enable));
   BUFX2 FE_PDC189_FE_OFN205_n (.Y(FE_PDN189_FE_OFN205_n),
	.A(FE_OFN205_n));
   BUFX2 FE_PDC188_FE_OFN165_enable (.Y(FE_PDN188_FE_OFN165_enable),
	.A(FE_PDN190_FE_OFN165_enable));
   BUFX2 FE_PDC187_n_62 (.Y(FE_PDN187_n_62),
	.A(FE_PDN201_n_62));
   BUFX2 FE_PDC186_FE_OFN17_reset (.Y(FE_PDN186_FE_OFN17_reset),
	.A(FE_OFN17_reset));
   BUFX2 FE_PDC185_FE_OFN168_n (.Y(FE_PDN185_FE_OFN168_n),
	.A(FE_OFN168_n));
   BUFX2 FE_PDC184_FE_OFN28_out_3 (.Y(FE_PDN184_FE_OFN28_out_3),
	.A(FE_PDN200_FE_OFN28_out_3));
   BUFX2 FE_PDC183_n_85 (.Y(FE_PDN183_n_85),
	.A(n_85));
   BUFX2 FE_PDC182_n_46 (.Y(FE_PDN182_n_46),
	.A(n_46));
   BUFX2 FE_PDC181_n_92 (.Y(FE_PDN181_n_92),
	.A(n_92));
   BUFX2 FE_PDC180_FE_OFN32_out_1 (.Y(FE_PDN180_FE_OFN32_out_1),
	.A(FE_OFN32_out_1));
   BUFX2 FE_PDC179_n_69 (.Y(FE_PDN179_n_69),
	.A(n_69));
   BUFX2 FE_PDC178_n_0 (.Y(FE_PDN178_n_0),
	.A(n_0));
   BUFX2 FE_PDC177_FE_OFN205_n (.Y(FE_PDN177_FE_OFN205_n),
	.A(FE_PDN189_FE_OFN205_n));
   BUFX2 FE_PDC176_FE_OFN204_n (.Y(FE_PDN176_FE_OFN204_n),
	.A(FE_OFN204_n));
   BUFX2 FE_PDC175_FE_OFN12_reset (.Y(FE_PDN175_FE_OFN12_reset),
	.A(FE_OFN12_reset));
   BUFX2 FE_PDC174_FE_OFN165_enable (.Y(FE_PDN174_FE_OFN165_enable),
	.A(FE_OFN165_enable));
   BUFX2 CTS_ccl_a_buf_00017 (.Y(CTS_7),
	.A(CTS_6));
   BUFX2 CTS_ccl_a_buf_00028 (.Y(CTS_6),
	.A(CTS_8));
   BUFX2 CTS_ccl_a_buf_00015 (.Y(CTS_4),
	.A(CTS_5));
   BUFX2 CTS_ccl_a_buf_00013 (.Y(CTS_3),
	.A(CTS_5));
   BUFX2 CTS_ccl_a_buf_00026 (.Y(CTS_5),
	.A(CTS_8));
   BUFX2 CTS_ccl_a_buf_00011 (.Y(CTS_2),
	.A(CTS_1));
   BUFX2 CTS_ccl_a_buf_00024 (.Y(CTS_1),
	.A(CTS_8));
   BUFX2 CTS_ccl_a_buf_00034 (.Y(CTS_8),
	.A(CTS_9));
   BUFX2 CTS_ccl_a_buf_00037 (.Y(CTS_9),
	.A(CTS_10));
   BUFX2 CTS_ccl_a_buf_00040 (.Y(CTS_10),
	.A(clk));
   BUFX2 FE_OFC173_enable (.Y(FE_OFN173_enable),
	.A(enable));
   BUFX2 FE_OFC172_FE_OFN27_out_4 (.Y(FE_OFN172_FE_OFN27_out_4),
	.A(FE_OFN188_FE_OFN27_out_4));
   BUFX2 FE_OFC171_reset (.Y(FE_PHN195_FE_OFN171_reset),
	.A(reset));
   BUFX2 FE_OFC169_n (.Y(FE_OFN169_n),
	.A(FE_OFN204_n));
   BUFX2 FE_OFC168_n (.Y(FE_OFN168_n),
	.A(FE_PDN177_FE_OFN205_n));
   BUFX2 FE_OFC218_n_71 (.Y(FE_OFN218_n_71),
	.A(n_71));
   BUFX2 FE_OFC214_n_72 (.Y(FE_OFN214_n_72),
	.A(n_72));
   BUFX2 FE_OFC213_n_90 (.Y(FE_OFN213_n_90),
	.A(n_90));
   BUFX2 FE_OFC210_n_42 (.Y(FE_OFN210_n_42),
	.A(n_42));
   BUFX2 FE_OFC209_n_35 (.Y(FE_OFN209_n_35),
	.A(n_35));
   BUFX2 FE_OFC207_n_62 (.Y(FE_OFN207_n_62),
	.A(FE_PDN187_n_62));
   BUFX2 FE_OFC206_n_83 (.Y(FE_OFN206_n_83),
	.A(n_83));
   BUFX2 FE_OFC205_n (.Y(FE_OFN205_n),
	.A(FE_OFN185_n_58));
   BUFX2 FE_OFC204_n_87 (.Y(FE_OFN204_n),
	.A(FE_OFN76_n_87));
   BUFX2 FE_OFC203_n_56 (.Y(FE_OFN203_n_56),
	.A(n_56));
   BUFX2 FE_OFC201_n_48 (.Y(FE_OFN201_n_48),
	.A(n_48));
   BUFX2 FE_OFC200_FE_OFN45_n_3 (.Y(FE_OFN200_FE_OFN45_n_3),
	.A(FE_OFN45_n_3));
   BUFX2 FE_OFC198_FE_OFN8_enable (.Y(FE_OFN198_FE_OFN8_enable),
	.A(FE_OFN8_enable));
   BUFX2 FE_OFC196_n_0 (.Y(FE_OFN196_n_0),
	.A(FE_PDN178_n_0));
   BUFX2 FE_OFC167_out_7 (.Y(out[7]),
	.A(FE_OFN64_out_7));
   BUFX2 FE_OFC165_out_1 (.Y(out[1]),
	.A(FE_OFN149_n));
   BUFX2 FE_OFC195_FE_OFN28_out_3 (.Y(FE_OFN195_FE_OFN28_out_3),
	.A(FE_PDN184_FE_OFN28_out_3));
   BUFX2 FE_OFC194_out_0 (.Y(out[0]),
	.A(FE_OFN66_out_0));
   BUFX2 FE_OFC193_out_3 (.Y(out[3]),
	.A(FE_OFN193_out_3));
   BUFX2 FE_OFC192_n_77 (.Y(FE_OFN192_n_77),
	.A(n_77));
   BUFX2 FE_OFC190_n_53 (.Y(FE_OFN190_n_53),
	.A(n_53));
   BUFX2 FE_OFC188_FE_OFN27_out_4 (.Y(FE_OFN188_FE_OFN27_out_4),
	.A(FE_OFN25_out_4));
   BUFX2 FE_OFC185_n_58 (.Y(FE_OFN185_n_58),
	.A(n_58));
   BUFX2 FE_OFC184_n_10 (.Y(FE_OFN184_n_10),
	.A(n_10));
   BUFX2 FE_OFC183_FE_OFN23_out_5 (.Y(FE_OFN183_FE_OFN23_out_5),
	.A(FE_OFN23_out_5));
   BUFX2 FE_OFC182_n_2 (.Y(FE_OFN182_n_2),
	.A(n_2));
   BUFX2 FE_OFC180_n_95 (.Y(FE_OFN180_n_95),
	.A(n_95));
   BUFX2 FE_OFC179_n_47 (.Y(FE_OFN179_n_47),
	.A(n_47));
   BUFX2 FE_OFC178_n_55 (.Y(FE_OFN178_n_55),
	.A(n_55));
   BUFX2 FE_OFC177_FE_OFN17_reset (.Y(FE_OFN177_FE_OFN17_reset),
	.A(FE_PDN186_FE_OFN17_reset));
   BUFX2 FE_OFC175_n_41 (.Y(FE_OFN175_n_41),
	.A(n_41));
   BUFX2 FE_OFC174_out_0__58 (.Y(FE_OFN174_out_0__58),
	.A(\out[0]_58 ));
   BUFX2 FE_OFC172_FE_OFN30_out_2 (.Y(FE_OFN172_FE_OFN30_out_2),
	.A(FE_OFN30_out_2));
   BUFX2 FE_OFC171_n_51 (.Y(FE_OFN171_n_51),
	.A(n_51));
   BUFX2 FE_OFC168_n_65 (.Y(FE_OFN168_n_65),
	.A(n_65));
   BUFX2 FE_OFC167_out_7__65 (.Y(FE_OFN167_out_7__65),
	.A(FE_PDN202_FE_OFN166_out_7__65));
   BUFX2 FE_OFC166_out_7__65 (.Y(FE_OFN166_out_7__65),
	.A(\out[7]_65 ));
   BUFX2 FE_OFC165_enable (.Y(FE_OFN165_enable),
	.A(FE_OFN173_enable));
   BUFX2 FE_OFC162_out_2 (.Y(out[2]),
	.A(FE_OFN162_out_2));
   BUFX2 FE_OFC161_out_3 (.Y(FE_OFN193_out_3),
	.A(FE_OFN151_n));
   BUFX2 FE_OFC160_out_4 (.Y(out[4]),
	.A(FE_OFN172_FE_OFN27_out_4));
   BUFX2 FE_OFC159_out_5 (.Y(out[5]),
	.A(FE_OFN183_FE_OFN23_out_5));
   BUFX2 FE_OFC157_out_6 (.Y(out[6]),
	.A(FE_OFN22_out_6));
   BUFX2 FE_OFC155_enable (.Y(FE_OFN155_n),
	.A(FE_PDN190_FE_OFN165_enable));
   BUFX2 FE_OFC151_out_3 (.Y(FE_OFN151_n),
	.A(FE_OFN195_FE_OFN28_out_3));
   BUFX2 FE_OFC149_out_1 (.Y(FE_OFN149_n),
	.A(FE_PDN180_FE_OFN32_out_1));
   BUFX2 FE_OFC148_n_87 (.Y(FE_OFN148_n),
	.A(FE_OFN78_n_87));
   BUFX2 FE_OFC145_n_81 (.Y(FE_OFN145_n),
	.A(n_81));
   BUFX2 FE_OFC144_n_96 (.Y(FE_OFN144_n_96),
	.A(n_96));
   BUFX2 FE_OFC142_n_94 (.Y(FE_OFN142_n_94),
	.A(n_94));
   BUFX2 FE_OFC138_n_88 (.Y(FE_OFN138_n_88),
	.A(n_88));
   BUFX2 FE_OFC136_n_85 (.Y(FE_OFN136_n_85),
	.A(FE_PDN183_n_85));
   BUFX2 FE_OFC135_n_84 (.Y(FE_OFN135_n_84),
	.A(n_84));
   BUFX2 FE_OFC133_n_82 (.Y(FE_OFN133_n_82),
	.A(n_82));
   BUFX2 FE_OFC132_n_80 (.Y(FE_OFN132_n_80),
	.A(n_80));
   BUFX2 FE_OFC129_n_76 (.Y(FE_OFN129_n_76),
	.A(n_76));
   BUFX2 FE_OFC124_n_75 (.Y(FE_OFN124_n_75),
	.A(n_75));
   BUFX2 FE_OFC123_n_74 (.Y(FE_OFN123_n_74),
	.A(n_74));
   BUFX2 FE_OFC119_n_70 (.Y(FE_OFN119_n_70),
	.A(n_70));
   BUFX2 FE_OFC117_n_68 (.Y(FE_OFN117_n_68),
	.A(n_68));
   BUFX2 FE_OFC116_n_67 (.Y(FE_OFN116_n_67),
	.A(n_67));
   BUFX2 FE_OFC113_n_149 (.Y(FE_OFN113_n_149),
	.A(n_149));
   BUFX2 FE_OFC112_n_66 (.Y(FE_OFN112_n_66),
	.A(n_66));
   BUFX2 FE_OFC111_n_63 (.Y(FE_OFN111_n_63),
	.A(n_63));
   BUFX2 FE_OFC110_n_60 (.Y(FE_OFN110_n_60),
	.A(n_60));
   BUFX2 FE_OFC109_n_148 (.Y(FE_OFN109_n_148),
	.A(n_148));
   BUFX2 FE_OFC108_n_61 (.Y(FE_OFN108_n_61),
	.A(n_61));
   BUFX2 FE_OFC107_n_59 (.Y(FE_OFN107_n_59),
	.A(n_59));
   BUFX2 FE_OFC106_n_57 (.Y(FE_OFN106_n_57),
	.A(n_57));
   BUFX2 FE_OFC103_n_58 (.Y(FE_OFN103_n_58),
	.A(FE_PDN185_FE_OFN168_n));
   BUFX2 FE_OFC97_n_52 (.Y(FE_OFN97_n_52),
	.A(n_52));
   BUFX2 FE_OFC94_n_51 (.Y(FE_OFN94_n_51),
	.A(FE_OFN171_n_51));
   BUFX2 FE_OFC90_n_47 (.Y(FE_OFN90_n_47),
	.A(FE_OFN179_n_47));
   BUFX2 FE_OFC88_n_46 (.Y(FE_OFN88_n_46),
	.A(FE_PDN182_n_46));
   BUFX2 FE_OFC86_n_87 (.Y(FE_OFN86_n_87),
	.A(FE_OFN81_n_87));
   BUFX2 FE_OFC81_n_87 (.Y(FE_OFN81_n_87),
	.A(FE_OFN169_n));
   BUFX2 FE_OFC78_n_87 (.Y(FE_OFN78_n_87),
	.A(FE_PDN176_FE_OFN204_n));
   BUFX2 FE_OFC76_n_87 (.Y(FE_OFN76_n_87),
	.A(n_87));
   BUFX2 FE_OFC75_n_49 (.Y(FE_OFN75_n_49),
	.A(n_49));
   BUFX2 FE_OFC71_n_37 (.Y(FE_OFN71_n_37),
	.A(n_37));
   BUFX2 FE_OFC69_n_33 (.Y(FE_OFN69_n_33),
	.A(n_33));
   BUFX2 FE_OFC68_n_24 (.Y(FE_OFN68_n_24),
	.A(n_24));
   BUFX2 FE_OFC61_out_0__58 (.Y(FE_OFN61_out_0__58),
	.A(FE_OFN174_out_0__58));
   BUFX2 FE_OFC58_n_11 (.Y(FE_OFN58_n_11),
	.A(FE_OFN57_n_11));
   BUFX2 FE_OFC57_n_11 (.Y(FE_OFN57_n_11),
	.A(n_11));
   BUFX2 FE_OFC56_n_10 (.Y(FE_OFN56_n_10),
	.A(FE_OFN55_n_10));
   BUFX2 FE_OFC55_n_10 (.Y(FE_OFN55_n_10),
	.A(FE_OFN184_n_10));
   BUFX2 FE_OFC51_n_8 (.Y(FE_OFN51_n_8),
	.A(n_8));
   BUFX2 FE_OFC47_n_6 (.Y(FE_OFN47_n_6),
	.A(n_6));
   BUFX2 FE_OFC45_n_3 (.Y(FE_OFN45_n_3),
	.A(n_3));
   BUFX2 FE_OFC42_n_2 (.Y(FE_OFN42_n_2),
	.A(FE_OFN182_n_2));
   BUFX2 FE_OFC38_n_1 (.Y(FE_OFN38_n_1),
	.A(n_1));
   BUFX2 FE_OFC37_n_0 (.Y(FE_OFN37_n_0),
	.A(FE_OFN196_n_0));
   BUFX2 FE_OFC31_out_2 (.Y(FE_OFN162_out_2),
	.A(FE_OFN172_FE_OFN30_out_2));
   BUFX2 FE_OFC21_out_6 (.Y(FE_OFN22_out_6),
	.A(FE_OFN21_out_6));
   BUFX2 FE_OFC19_reset (.Y(FE_OFN19_reset),
	.A(FE_OFN177_FE_OFN17_reset));
   BUFX2 FE_OFC17_reset (.Y(FE_OFN17_reset),
	.A(FE_OFN14_reset));
   BUFX2 FE_OFC14_reset (.Y(FE_OFN14_reset),
	.A(FE_PDN175_FE_OFN12_reset));
   BUFX2 FE_OFC12_reset (.Y(FE_OFN12_reset),
	.A(FE_PHN191_FE_OFN171_reset));
   BUFX2 FE_OFC8_enable (.Y(FE_OFN8_enable),
	.A(FE_OFN4_enable));
   BUFX2 FE_OFC7_enable (.Y(FE_OFN7_enable),
	.A(FE_OFN5_enable));
   BUFX2 FE_OFC5_enable (.Y(FE_OFN5_enable),
	.A(FE_OFN155_n));
   BUFX2 FE_OFC4_enable (.Y(FE_OFN4_enable),
	.A(FE_PDN188_FE_OFN165_enable));
   DFFX1 \out_reg[7]  (.Q(\out[7]_65 ),
	.QN(n_8),
	.D(FE_OFN144_n_96),
	.CK(CTS_3));
   NOR2X1 g203__8780 (.Y(n_96),
	.A(FE_OFN19_reset),
	.B(FE_OFN180_n_95));
   DFFX1 \out_reg[6]  (.Q(FE_OFN21_out_6),
	.QN(n_2),
	.D(FE_OFN142_n_94),
	.CK(CTS_3));
   NOR2X1 g205__4296 (.Y(n_95),
	.A(FE_OFN69_n_33),
	.B(n_91));
   NOR2X1 g206__3772 (.Y(n_94),
	.A(FE_OFN19_reset),
	.B(FE_PDN181_n_92));
   DFFX1 \out_reg[5]  (.Q(FE_OFN23_out_5),
	.QN(n_10),
	.D(n_93),
	.CK(CTS_4));
   NOR2X1 g207__1474 (.Y(n_93),
	.A(FE_OFN14_reset),
	.B(n_89));
   NOR2X1 g209__4547 (.Y(n_92),
	.A(FE_OFN71_n_37),
	.B(FE_OFN138_n_88));
   NOR2X1 g210__9682 (.Y(n_91),
	.A(FE_OFN148_n),
	.B(FE_OFN213_n_90));
   DFFX1 \out_reg[4]  (.Q(FE_OFN25_out_4),
	.QN(n_3),
	.D(n_86),
	.CK(CTS_2));
   NOR2X1 g213__2683 (.Y(n_90),
	.A(FE_OFN136_n_85),
	.B(FE_OFN133_n_82));
   NOR2X1 g214__1309 (.Y(n_89),
	.A(n_44),
	.B(FE_OFN135_n_84));
   NOR2X1 g215__6877 (.Y(n_88),
	.A(FE_OFN148_n),
	.B(FE_OFN206_n_83));
   DFFX1 \out_reg[3]  (.Q(FE_OFN28_out_3),
	.QN(n_0),
	.D(n_79),
	.CK(CTS_2));
   NOR2X1 g211__2900 (.Y(n_86),
	.A(FE_PHN199_FE_OFN171_reset),
	.B(FE_OFN132_n_80));
   NOR2X1 g216__2391 (.Y(n_85),
	.A(FE_OFN51_n_8),
	.B(n_78));
   NOR2X1 g219__7675 (.Y(n_84),
	.A(FE_OFN78_n_87),
	.B(FE_OFN129_n_76));
   NAND2X1 g222__7118 (.Y(n_83),
	.A(FE_OFN192_n_77),
	.B(FE_OFN145_n));
   NOR2X1 g217__8757 (.Y(n_82),
	.A(FE_OFN167_out_7__65),
	.B(FE_OFN145_n));
   NOR2X1 g220__1786 (.Y(n_80),
	.A(n_39),
	.B(FE_OFN214_n_72));
   NOR2X1 g221__5953 (.Y(n_79),
	.A(FE_OFN12_reset),
	.B(FE_OFN123_n_74));
   DFFX1 \out_reg[2]  (.Q(FE_OFN30_out_2),
	.QN(n_11),
	.D(n_73),
	.CK(CTS_4));
   DFFX1 \out_reg[1]  (.Q(FE_OFN32_out_1),
	.QN(n_1),
	.D(FE_OFN218_n_71),
	.CK(CTS_7));
   INVX1 g223 (.Y(n_78),
	.A(FE_OFN145_n));
   NAND2X1 g227__5703 (.Y(n_77),
	.A(FE_OFN42_n_2),
	.B(FE_OFN124_n_75));
   NAND2X1 g228__7114 (.Y(n_76),
	.A(FE_OFN117_n_68),
	.B(FE_OFN124_n_75));
   NOR2X1 g224__5266 (.Y(n_74),
	.A(FE_OFN175_n_41),
	.B(FE_OFN116_n_67));
   NAND2X1 g225__2250 (.Y(n_81),
	.A(n_19),
	.B(FE_OFN119_n_70));
   NOR2X1 g229__6083 (.Y(n_73),
	.A(FE_OFN14_reset),
	.B(FE_PDN179_n_69));
   NOR2X1 g230__2703 (.Y(n_72),
	.A(FE_OFN78_n_87),
	.B(FE_OFN168_n_65));
   NOR2X1 g231__5795 (.Y(n_71),
	.A(FE_OFN17_reset),
	.B(FE_OFN112_n_66));
   INVX1 g234 (.Y(n_75),
	.A(FE_OFN119_n_70));
   NOR2X1 g232__7344 (.Y(n_69),
	.A(FE_OFN209_n_35),
	.B(FE_OFN111_n_63));
   NAND2X1 g233__1840 (.Y(n_68),
	.A(FE_OFN56_n_10),
	.B(FE_OFN113_n_149));
   NOR2X1 g235__5019 (.Y(n_67),
	.A(FE_OFN169_n),
	.B(FE_OFN110_n_60));
   NOR2X1 g238__1857 (.Y(n_66),
	.A(FE_OFN210_n_42),
	.B(FE_OFN108_n_61));
   DFFX1 \out_reg[0]  (.Q(\out[0]_58 ),
	.QN(n_6),
	.D(FE_OFN207_n_62),
	.CK(CTS_7));
   NAND2X1 g236__9906 (.Y(n_65),
	.A(FE_OFN107_n_59),
	.B(FE_OFN113_n_149));
   NOR2X1 g237__8780 (.Y(n_70),
	.A(FE_OFN56_n_10),
	.B(FE_OFN113_n_149));
   NOR2X1 g242__4296 (.Y(n_63),
	.A(FE_OFN81_n_87),
	.B(FE_OFN106_n_57));
   NOR2X1 g247__3772 (.Y(n_62),
	.A(FE_OFN177_FE_OFN17_reset),
	.B(FE_OFN178_n_55));
   NOR2X1 g248__1474 (.Y(n_61),
	.A(FE_OFN86_n_87),
	.B(FE_OFN203_n_56));
   NAND2X1 g239__4547 (.Y(n_60),
	.A(FE_OFN190_n_53),
	.B(FE_OFN205_n));
   NAND2X1 g241__2683 (.Y(n_59),
	.A(FE_OFN200_FE_OFN45_n_3),
	.B(FE_OFN103_n_58));
   NAND2X1 g249__1309 (.Y(n_57),
	.A(FE_OFN201_n_48),
	.B(FE_OFN97_n_52));
   NAND2X1 g253__6877 (.Y(n_56),
	.A(FE_OFN90_n_47),
	.B(n_50));
   NOR2X1 g254__2900 (.Y(n_55),
	.A(n_45),
	.B(FE_OFN75_n_49));
   NAND2X1 g245__2391 (.Y(n_53),
	.A(FE_OFN37_n_0),
	.B(FE_OFN97_n_52));
   NAND2X1 g246__7675 (.Y(n_58),
	.A(n_22),
	.B(FE_OFN94_n_51));
   INVX1 g250 (.Y(n_52),
	.A(FE_OFN94_n_51));
   INVX1 g255 (.Y(n_50),
	.A(FE_OFN88_n_46));
   NOR2X1 g266__7118 (.Y(n_49),
	.A(FE_OFN198_FE_OFN8_enable),
	.B(FE_OFN47_n_6));
   NAND2X1 g251__8757 (.Y(n_48),
	.A(FE_OFN58_n_11),
	.B(FE_OFN90_n_47));
   NOR2X1 g252__1786 (.Y(n_51),
	.A(FE_OFN58_n_11),
	.B(FE_OFN90_n_47));
   NOR2X1 g257__5953 (.Y(n_46),
	.A(FE_OFN61_out_0__58),
	.B(FE_OFN68_n_24));
   NOR2X1 g265__5703 (.Y(n_45),
	.A(FE_OFN86_n_87),
	.B(FE_OFN61_out_0__58));
   NOR2X1 g259__7114 (.Y(n_44),
	.A(FE_OFN5_enable),
	.B(FE_OFN55_n_10));
   NOR2X1 g258__5266 (.Y(n_42),
	.A(FE_OFN198_FE_OFN8_enable),
	.B(FE_OFN38_n_1));
   NOR2X1 g256__2250 (.Y(n_41),
	.A(FE_OFN4_enable),
	.B(FE_OFN196_n_0));
   NOR2X1 g261__6083 (.Y(n_39),
	.A(FE_OFN155_n),
	.B(FE_OFN45_n_3));
   NOR2X1 g264__2703 (.Y(n_37),
	.A(FE_OFN7_enable),
	.B(FE_OFN182_n_2));
   NOR2X1 g263__5795 (.Y(n_35),
	.A(FE_OFN8_enable),
	.B(FE_OFN58_n_11));
   NOR2X1 g262__7344 (.Y(n_33),
	.A(FE_OFN7_enable),
	.B(FE_OFN51_n_8));
   NAND2X1 g260__1840 (.Y(n_47),
	.A(FE_OFN68_n_24),
	.B(FE_OFN61_out_0__58));
   INVX1 g283 (.Y(FE_OFN64_out_7),
	.A(n_8));
   INVX1 g303 (.Y(FE_OFN66_out_0),
	.A(FE_OFN47_n_6));
   INVX1 g291 (.Y(n_19),
	.A(FE_OFN42_n_2));
   INVX1 g269 (.Y(n_24),
	.A(FE_OFN38_n_1));
   INVX1 g278 (.Y(n_22),
	.A(FE_OFN37_n_0));
   INVX1 g305 (.Y(n_87),
	.A(FE_OFN165_enable));
   INVX1 g3 (.Y(n_149),
	.A(FE_OFN109_n_148));
   NOR2X1 g2 (.Y(n_148),
	.A(FE_OFN200_FE_OFN45_n_3),
	.B(FE_OFN103_n_58));
endmodule

