
// Generated by Cadence Genus(TM) Synthesis Solution 18.15-s055_1
// Generated on: Sep 21 2021 20:16:37 CEST (Sep 21 2021 18:16:37 UTC)

// Verification Directory fv/counter 

module counter(out, enable, clk, reset);
  input enable, clk, reset;
  output [7:0] out;
  wire enable, clk, reset;
  wire [7:0] out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66;
  DFFX1 \out_reg[7] (.CK (clk), .D (n_66), .Q (out[7]), .QN (n_5));
  NOR2X1 g227__8780(.A (reset), .B (n_64), .Y (n_66));
  DFFX1 \out_reg[6] (.CK (clk), .D (n_65), .Q (out[6]), .QN (n_8));
  NOR2X1 g230__4296(.A (reset), .B (n_62), .Y (n_65));
  NOR2X1 g229__3772(.A (n_6), .B (n_61), .Y (n_64));
  DFFX1 \out_reg[5] (.CK (clk), .D (n_63), .Q (out[5]), .QN (n_34));
  NOR2X1 g231__1474(.A (reset), .B (n_59), .Y (n_63));
  NOR2X1 g233__4547(.A (n_9), .B (n_58), .Y (n_62));
  NOR2X1 g234__9682(.A (n_57), .B (n_60), .Y (n_61));
  DFFX1 \out_reg[4] (.CK (clk), .D (n_56), .Q (out[4]), .QN (n_10));
  NOR2X1 g237__2683(.A (n_54), .B (n_52), .Y (n_60));
  NOR2X1 g238__1309(.A (n_12), .B (n_53), .Y (n_59));
  NOR2X1 g239__6877(.A (n_57), .B (n_55), .Y (n_58));
  NOR2X1 g235__2900(.A (reset), .B (n_50), .Y (n_56));
  DFFX1 \out_reg[3] (.CK (clk), .D (n_49), .Q (out[3]), .QN (n_14));
  NAND2X1 g246__2391(.A (n_47), .B (n_51), .Y (n_55));
  NOR2X1 g240__7675(.A (n_5), .B (n_48), .Y (n_54));
  NOR2X1 g243__7118(.A (n_57), .B (n_46), .Y (n_53));
  NOR2X1 g241__8757(.A (out[7]), .B (n_51), .Y (n_52));
  DFFX1 \out_reg[2] (.CK (clk), .D (n_43), .Q (out[2]), .QN (n_17));
  NOR2X1 g244__1786(.A (n_11), .B (n_42), .Y (n_50));
  NOR2X1 g245__5953(.A (reset), .B (n_44), .Y (n_49));
  INVX1 g247(.A (n_51), .Y (n_48));
  NAND2X1 g251__5703(.A (n_8), .B (n_45), .Y (n_47));
  NAND2X1 g252__7114(.A (n_37), .B (n_45), .Y (n_46));
  NOR2X1 g248__5266(.A (n_15), .B (n_40), .Y (n_44));
  NAND2X1 g249__2250(.A (out[6]), .B (n_41), .Y (n_51));
  NOR2X1 g253__6083(.A (reset), .B (n_38), .Y (n_43));
  NOR2X1 g254__2703(.A (n_57), .B (n_36), .Y (n_42));
  DFFX1 \out_reg[1] (.CK (clk), .D (n_39), .Q (out[1]), .QN (n_0));
  INVX1 g258(.A (n_41), .Y (n_45));
  NOR2X1 g259__5795(.A (n_57), .B (n_32), .Y (n_40));
  NOR2X1 g255__7344(.A (reset), .B (n_33), .Y (n_39));
  NOR2X1 g256__1840(.A (n_7), .B (n_31), .Y (n_38));
  NAND2X1 g257__5019(.A (n_34), .B (n_35), .Y (n_37));
  NAND2X1 g260__1857(.A (n_30), .B (n_35), .Y (n_36));
  NOR2X1 g261__9906(.A (n_34), .B (n_35), .Y (n_41));
  NAND2X1 g267__8780(.A (out[4]), .B (n_28), .Y (n_35));
  DFFX1 \out_reg[0] (.CK (clk), .D (n_26), .Q (out[0]), .QN (n_1));
  NOR2X1 g262__4296(.A (n_16), .B (n_25), .Y (n_33));
  NAND2X1 g263__3772(.A (n_27), .B (n_29), .Y (n_32));
  NOR2X1 g266__1474(.A (n_57), .B (n_24), .Y (n_31));
  NAND2X1 g265__4547(.A (n_10), .B (n_29), .Y (n_30));
  INVX1 g268(.A (n_29), .Y (n_28));
  NAND2X1 g269__9682(.A (n_14), .B (n_23), .Y (n_27));
  NOR2X1 g271__2683(.A (reset), .B (n_20), .Y (n_26));
  NOR2X1 g272__1309(.A (n_57), .B (n_21), .Y (n_25));
  NAND2X1 g273__6877(.A (n_19), .B (n_23), .Y (n_24));
  NAND2X1 g270__2900(.A (out[3]), .B (n_22), .Y (n_29));
  INVX1 g274(.A (n_22), .Y (n_23));
  NAND2X1 g277__2391(.A (n_18), .B (n_13), .Y (n_21));
  NOR2X1 g278__7675(.A (n_3), .B (n_4), .Y (n_20));
  NAND2X1 g275__7118(.A (n_17), .B (n_18), .Y (n_19));
  NOR2X1 g276__8757(.A (n_17), .B (n_18), .Y (n_22));
  NOR2X1 g282__1786(.A (enable), .B (n_0), .Y (n_16));
  NOR2X1 g280__5953(.A (enable), .B (n_14), .Y (n_15));
  INVX1 g279(.A (n_2), .Y (n_13));
  NOR2X1 g283__5703(.A (enable), .B (n_34), .Y (n_12));
  NOR2X1 g285__7114(.A (enable), .B (n_10), .Y (n_11));
  NOR2X1 g288__5266(.A (enable), .B (n_8), .Y (n_9));
  NOR2X1 g287__2250(.A (enable), .B (n_17), .Y (n_7));
  NOR2X1 g286__6083(.A (enable), .B (n_5), .Y (n_6));
  NOR2X1 g290__2703(.A (enable), .B (n_1), .Y (n_4));
  NOR2X1 g289__5795(.A (n_57), .B (out[0]), .Y (n_3));
  NOR2X1 g281__7344(.A (out[0]), .B (out[1]), .Y (n_2));
  NAND2X1 g284__1840(.A (out[1]), .B (out[0]), .Y (n_18));
  INVX1 g299(.A (enable), .Y (n_57));
endmodule

